# fly.toml app configuration file generated for quests-app on 2023-11-02T14:26:04+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quests-app"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
