# fly.toml app configuration file generated for quests-api-67 on 2023-09-22T14:10:02+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quests-api-67"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
