name: Prisma db push
on:
  push:
    branches:
      - main
jobs:
  db-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Deploy Migrations
        run: bunx prisma db push --schema=./packages/server/prisma/schema.prisma --skip-generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
